
import { Inter } from "next/font/google";
import "./globals.css";
import { HomessProvider } from "./context/HomessContext";
import localFont from "next/font/local";


const Theboys = localFont({
  src: [
    {
      path: "../../public/fonts/Theboysfont.ttf",
      weight: "400",
    },
   
  ],
});


/*  const TheboysFonts = localFont({
  src: [
    {
      path: "../../public/fonts/AirAmericana-Light.ttf",
      weight: "400",
   
    },
   
  ],
}); */
export const metadata = {
  title: "The Boys",
  description: "Generated by create next app",

  icons: {
    icon: "/the-boys.ico",
  },
};
export default function RootLayout({ children }) {
  return (
    <HomessProvider>
    <html lang="en">
  
      <body className={` ${Theboys.className}`}>{children}</body>
     
    </html>
    </HomessProvider>
    
  );
}
